services:
  # Redis 服务，用于缓存、会话管理等，提供键值存储功能
  judgeMore-redis:
    container_name: judgeMore-redis
    image: redis:bookworm
    volumes:
      - ./data/redis:/data
    # 移除端口映射，只在内部网络访问
    networks:
      - judgeMore
    env_file:
      - "./env/redis.env"

  # MySQL 服务，提供关系型数据库，用于存储结构化数据
  judgeMore-mysql:
    container_name: judgeMore-mysql
    image: mysql:9.0.1
    env_file:
      - "./env/mysql.env"
    # 移除端口映射，只在内部网络访问
    networks:
      - judgeMore
    volumes:
      - ../config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  # 你的应用服务 - 仅向外暴露此服务的端口
  judgeMore_server:
    container_name: judgeMore_server
    image: judgemore:latest
    ports:
      - "8080:8080"  # 仅向外暴露应用服务的端口
    networks:
      - judgeMore
    volumes:
      - ../config/:/app/config/
      - ./logs:/app/logs        # 挂载日志目录
    env_file:
      - "./env/app.env"          # 应用环境变量
    depends_on:
      - judgeMore-redis
      - judgeMore-mysql
      - judgeMore-elasticsearch
    restart: unless-stopped

  judgeMore-elasticsearch:
    image: elasticsearch:8.4.2
    container_name: judgeMore-elasticsearch
    env_file:
      - ./env/es.env
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://elasticsearch:9200/_cluster/health || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../config/elasticsearch/config:/usr/share/elasticsearch/config
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ../config/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    restart: always
    networks:
      - judgeMore
    mem_limit: 2g

networks:
  judgeMore:
    driver: bridge
    name: judgeMore
