mysql:
  addr: 0.0.0.0:3306
  database: judgeMore
  username: judgeMore
  password: judgeMore
  charset: utf8mb4

smtp:
  host: "smtp.163.com"
  port: 465
  user: "xx@163.com"
  password: "xxxxxxx"
  from: "xxxxxx@163.com"
  from_name: "judgeMore"

openai:
  api-key: ""
  api-model: ""
  api-url: ""
oss:
  bucket: ""
  accessKey: ""
  secretKey: ""
  domain: "https://portal.qiniu.com/"
  region: ""


redis:
  addr: 127.0.0.1:6379
  username: "default"
  password: "judgeMore"

services:
  main:
    name : main
    load-balance: true
    addr:
      - 0.0.0.0:9999
      - 127.0.0.1:10001
