mysql:
  addr: 0.0.0.0:3306
  database: judgeMore
  username: judgeMore
  password: judgeMore
  charset: utf8mb4

smtp:
  host: "smtp.163.com"
  port: 465
  user: "m17850991643@163.com"
  password: "DPe3RHC7Ez7eCbWB"
  from: "m17850991643@163.com"
  from_name: "judgeMore"


etcd:
  addr: 127.0.0.1:2379

redis:
  addr: 127.0.0.1:6379
  username: "default"
  password: "judgeMore"

services:
  main:
    name : gateway
    load-balance: true
    addr:
      - 0.0.0.0:9999
      - 127.0.0.1:10001
